services:
  # Monolithic Service (Backend + Frontend)
  - type: web
    name: flizlen-app
    runtime: python
    buildCommand: ./render_build.sh
    startCommand: bash start_render.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GEMINI_API_KEY
        sync: false # User will input this in dashboard
    plan: free
